theme: jekyll-theme-cayman

# Additional
title: Aurora
description: [This is personal blog focused on multi-cloud technologies and Infrastructure as Code (IaC). </br> The notes and opinion expressed on this blog are on my own.]
